src/Invento/Areas/Payment/Models/Voucher.cs
using System;
using Invento.Areas.CompanyAdmin.Models.Company;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Invento.Areas.Payment.Models
{
    public class Voucher
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int VoucherID { get; set; }
        
        [Display(Name = "Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }

        public string Particulars { get; set; }

        [Display(Name = "Import Bill ID")]
        public string ImportExportID { get; set; }

        [Display(Name = "Currency")]
        [ForeignKey("Currency")]
        public int CurrencyID { get; set; }
        public virtual Currency Currency { get; set; }

        [Display(Name = "Ex-Rate")]
        public string ExternalRef { get; set; }


        public int CompanyID { get; set; }
        public DateTime CreationDate { get; set; }
        public string CreatedBy { get; set; }

        public virtual ICollection<VoucherItems> VoucherItems { get; set; }        
    }
}

src/Invento/Areas/Reports/Controllers/AnalysisController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Invento.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Invento.Areas.Reports.Models;
using System;
using System.Collections.Generic;
using Invento.Areas.CompanyAdmin.Models.Company;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Invento.Areas.Reports.Controllers
{
    [Authorize(Roles = "BiznsBook")]
    [Area("Reports")]
    [Route("Reports/[controller]")]
    public class AnalysisController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AnalysisController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Route("[action]")]
        [Authorize(Roles = "Reports,CompanyAdmin")]
        public IActionResult Index()
        {
            return View();
        }

        [Route("[action]")]
        [Authorize(Roles = "Reports,CompanyAdmin")]
        public IActionResult AmountView(AnalysisVM model)
        {
            string CompId = User.Claims.Where(r => r.Type == "CompanyID").FirstOrDefault().Value;
            int CompID = Convert.ToInt32(CompId);
            DateTime.Now.AddYears(-1);

            int MainPartyAcc = _context.MainAccount.Where(r => r.CompanyID == CompID).Where(r => r.MainAccountNumber == "00").FirstOrDefault().MainAccountID;
            int SubPartyAcc = _context.SubAccount.Where(r => r.CompanyID == CompID).Where(r => r.MainAccountID == MainPartyAcc).Where(r => r.SubAccountNumber == "0000").FirstOrDefault().SubAccountID;

            List<decimal> listReceviable= new List<decimal>();
            List<decimal> listPayable = new List<decimal>();

            if(model.Party == null)
            {
                var Receivable = (from r in _context.CashFlow
                                  where r.CompanyID == CompID
                                  where r.MainAccountID == MainPartyAcc
                                  where r.SubAccountID == SubPartyAcc
                                  where r.PartiesID != null
                                  group r by r.PartiesID into g
                                  select new
                                  {
                                      ID = (int)g.Key,
                                      OpeningBalance = g.Select(x => x.TransactionAccount.OpeningBalance).FirstOrDefault(),
                                      credit = g.Sum(x => x.Credit),
                                      debit = g.Sum(x => x.Debit),
                                  }).ToList();

                foreach (var item in Receivable)
                {
                    decimal XYZ = item.OpeningBalance + item.debit - item.credit;
                    if (XYZ > 0)
                    {
                        listReceviable.Add(XYZ);
                    }
                }
                listReceviable.Sum();

                var Payable = (from r in _context.CashFlow
                               where r.CompanyID == CompID
                               where r.MainAccountID == MainPartyAcc
                               where r.SubAccountID == SubPartyAcc
                               where r.PartiesID != null
                               group r by r.PartiesID into g
                               select new
                               {
                                   ID = (int)g.Key,
                                   OpeningBalance = g.Select(x => x.TransactionAccount.OpeningBalance).FirstOrDefault(),
                                   credit = g.Sum(x => x.Credit),
                                   debit = g.Sum(x => x.Debit)
                               }).ToList();
                foreach (var item in Payable)
                {
                    decimal XYZ = item.OpeningBalance - item.credit + item.debit;
                    if (XYZ < 0)
                    {
                        listPayable.Add(XYZ);
                    }
                }
                model.Deci1 = listReceviable.Sum();
                model.Deci2 = listPayable.Sum();
            }
            else
            {
                var Receivable = (from r in _context.CashFlow
                                  where r.CompanyID == CompID
                                  where r.MainAccountID == MainPartyAcc
                                  where r.SubAccountID == SubPartyAcc
                                  where r.PartiesID == model.Party
                                  group r by r.PartiesID into g
                                  select new
                                  {
                                      ID = (int)g.Key,
                                      OpeningBalance = g.Select(x => x.TransactionAccount.OpeningBalance).FirstOrDefault(),
                                      credit = g.Sum(x => x.Credit),
                                      debit = g.Sum(x => x.Debit),
                                  }).ToList();

                foreach (var item in Receivable)
                {
                    decimal XYZ = item.OpeningBalance + item.debit - item.credit;
                    if (XYZ > 0)
                    {
                        listReceviable.Add(XYZ);
                    }
                }
                listReceviable.Sum();

                var Payable = (from r in _context.CashFlow
                               where r.CompanyID == CompID
                               where r.MainAccountID == MainPartyAcc
                               where r.SubAccountID == SubPartyAcc
                               where r.PartiesID == model.Party
                               group r by r.PartiesID into g
                               select new
                               {
                                   ID = (int)g.Key,
                                   OpeningBalance = g.Select(x => x.TransactionAccount.OpeningBalance).FirstOrDefault(),
                                   credit = g.Sum(x => x.Credit),
                                   debit = g.Sum(x => x.Debit)
                               }).ToList();
                foreach (var item in Payable)
                {
                    decimal XYZ = item.OpeningBalance - item.credit + item.debit;
                    if (XYZ < 0)
                    {
                        listPayable.Add(XYZ);
                    }
                }
                model.Deci1 = listReceviable.Sum();
                model.Deci2 = listPayable.Sum();
            }

            var partyList = new List<Parties>();
            partyList = _context.Parties.Where(r => r.CompanyID == CompID).ToList();
            model.PartyList = new SelectList(partyList, "PartiesID", "PartyName");
           
            return View(model);
        }

        [Route("[action]")]
        [Authorize(Roles = "Reports,CompanyAdmin")]
        public IActionResult VoucherView(AnalysisVM model)
        {
            string CompId = User.Claims.Where(r => r.Type == "CompanyID").FirstOrDefault().Value;
            int CompID = Convert.ToInt32(CompId);
 
            if (model.Period == 0)
            {
                DateTime SearchDate = DateTime.Now.AddYears(-1);

                model.Deci1 = _context.CashInBank.Where(r => r.CompanyID == CompID).Where(r => r.Date >= SearchDate).Sum(r => r.Amount);
                model.Deci2 = _context.CashPayment.Where(r => r.CompanyID == CompID).Where(r => r.Date >= SearchDate).Sum(r => r.Amount);
                model.Deci3 = _context.CashReceipt.Where(r => r.CompanyID == CompID).Where(r => r.Date >= SearchDate).Sum(r => r.Amount);
                model.Deci4 = _context.ChequePayment.Where(r => r.CompanyID == CompID).Where(r => r.Date >= SearchDate).Sum(r => r.Amount);
                model.Deci5 = _context.ChequeReceipt.Where(r => r.CompanyID == CompID).Where(r => r.Date >= SearchDate).Sum(r => r.Amount);
                model.Deci6 = _context.VoucherItems.Where(r => r.CompanyID == CompID).Where(r => r.Voucher.Date >= SearchDate).Sum(r => r.Credit);
                model.Deci7 = _context.VoucherItems.Where(r => r.CompanyID == CompID).Where(r => r.Voucher.Date >= SearchDate).Sum(r => r.Debit);
            }
            else if (model.Period == 1)
            {
                DateTime SearchDate = DateTime.Now.AddMonths(-1);

                model.Deci1 = _context.CashInBank.Where(r => r.CompanyID == CompID).Where(r => r.Date >= SearchDate).Sum(r => r.Amount);
                model.Deci2 = _context.CashPayment.Where(r => r.CompanyID == CompID).Where(r => r.Date >= SearchDate).Sum(r => r.Amount);
                model.Deci3 = _context.CashReceipt.Where(r => r.CompanyID == CompID).Where(r => r.Date >= SearchDate).Sum(r => r.Amount);
                model.Deci4 = _context.ChequePayment.Where(r => r.CompanyID == CompID).Where(r => r.Date >= SearchDate).Sum(r => r.Amount);
                model.Deci5 = _context.ChequeReceipt.Where(r => r.CompanyID == CompID).Where(r => r.Date >= SearchDate).Sum(r => r.Amount);
                model.Deci6 = _context.VoucherItems.Where(r => r.CompanyID == CompID).Where(r => r.Voucher.Date >= SearchDate).Sum(r => r.Credit);
                model.Deci7 = _context.VoucherItems.Where(r => r.CompanyID == CompID).Where(r => r.Voucher.Date >= SearchDate).Sum(r => r.Debit);
            }
            else if (model.Period == 2)
            {
                DateTime SearchDate = DateTime.Now.AddDays(-1);

                model.Deci1 = _context.CashInBank.Where(r => r.CompanyID == CompID).Where(r => r.Date >= SearchDate).Sum(r => r.Amount);
                model.Deci2 = _context.CashPayment.Where(r => r.CompanyID == CompID).Where(r => r.Date >= SearchDate).Sum(r => r.Amount);
                model.Deci3 = _context.CashReceipt.Where(r => r.CompanyID == CompID).Where(r => r.Date >= SearchDate).Sum(r => r.Amount);

src/Invento/Areas/Reports/Views/Analysis/AmountView.cshtml
@model Invento.Areas.Reports.Models.AnalysisVM
@{
    ViewData["Title"] = "Analysis - Amount View";
    if (User.IsInRole("CompanyAdmin"))
    {
        Layout = "~/Views/Shared/_LayoutCompanyAdmin.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_LayoutCompanyUser.cshtml";
    }
}

<div class="">
    <div class="well" style="padding-bottom:5px">
        <div class="row">
            <form asp-action="AmountView" asp-controller="Analysis" method="get">
                <div class="input-group">
                    <span class="glyphicon glyphicon-stats glyphicon-bold " style="font-size: 1.5em; padding-left:10px;color:darkblue" aria-hidden="true"></span>
                    <span style="font-family:'Times New Roman', Times, serif ; font-weight:bolder ; font-size:x-large ; margin-left:15px">Receivable Payable View</span>
                    <div class="col-md-3 pull-right">
                        <select class="form-control" asp-items="@Model.PartyList"  name="Party" id="Party">
                            <option selected>All Party Accounts</option>
                        </select>
                    </div>
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit" style="margin-right:50px"><span class="glyphicon glyphicon-search"></span></button>
                    </span>
                </div>
            </form>
        </div>
    </div>
    
    <div class="row">
        <div class="col-lg-12 ">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h1 class="panel-title">
                        Amount Receivable &amp; Payable View
                    </h1>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-8">
                            <canvas id="mycanvas" width="700" height="400"></canvas>
                        </div>
                        <div class="col-lg-3 pull-right">
                            <div class="row">
                                <br /><br /><br />
                                <div style="background-color:cornflowerblue" title="Amount Receivable"><p style="font-weight:bolder;padding-left:5px">Amount Receivable</p></div>
                                <div style="background-color:lightgreen" title="Amount Payable"><p style="font-weight:bolder;padding-left:5px">Amount Payable</p></div>
                               </div>
                        </div>
                    </div>                       
                </div>
            </div>
        </div>         
    </div>    
       
</div>
 
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js"></script>
 
    <script>
        $(document).ready(function () {
            @*var ctx = $("#mycanvas").get(0).getContext("2d");
            var data = [
                {
                    value: @Model.Deci1,
                    color: "cornflowerblue",
                    highlight: "#f76a5d",
                    label: "Amount to be Received."
                },
                {
                    value: @Model.Deci2,
                    color: "lightgreen",
                    highlight: "#f76a5d",
                    label: "Amount to Be Paid."
                }  
            ];
            var piechart = new Chart(ctx).Pie(data);*@
            var ctx = $("#mycanvas").get(0).getContext("2d");

            var data = [
                {
                    value: @Model.Deci1,
                    color: "cornflowerblue",
                    highlight: "lightskyblue",
                    label: "Amount to be Received."
                },
                {
                    value: @Model.Deci2,
                    color: "lightgreen",
                    highlight: "yellowgreen",
                    label: "Amount to Be Paid."
                } 
            ];

            var chart = new Chart(ctx).Doughnut(data);
        });

    </script>

src/Invento/Areas/Reports/Views/Analysis/PurchaseSaleViewMonthly.cshtml
@model Invento.Areas.Reports.Models.AnalysisVM
@{
    ViewData["Title"] = "Analysis-Purchase Sale View Monthly";
    if (User.IsInRole("CompanyAdmin"))
    {
        Layout = "~/Views/Shared/_LayoutCompanyAdmin.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_LayoutCompanyUser.cshtml";
    }
}

<div>
    <div class="well" style="padding-bottom:5px">
        <div class="row">
            <span class="glyphicon glyphicon-stats glyphicon-bold " style="font-size: 1.5em; padding-left:10px;color:darkblue" aria-hidden="true"></span>
            <span style="font-family:'Times New Roman', Times, serif ; font-weight:bolder ; font-size:x-large ; margin-left:15px">Purchase Sale Analysis</span>
      </div>
    </div>
         
    <div class="row" id="secondChart">
        <div class="col-lg-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div>
                        <form asp-action="PurchaseSaleViewMonthly" asp-controller="Analysis" method="get" style="padding-top:0px">
                            <div class="input-group">
                                <span class="panel-title">
                                    Purchase Sale Monthly Analysis
                                </span>
                                <input type="hidden" asp-for="LineChartType" value="1" />                                
                                <div class="col-md-2 pull-right">
                                    <select asp-for="Period" class="form-control">
                                        <option value="@DateTime.Now.Year">@DateTime.Now.Year</option>
                                        <option value="@DateTime.Now.AddYears(-1).Year">@DateTime.Now.AddYears(-1).Year</option>
                                        <option value="@DateTime.Now.AddYears(-2).Year">@DateTime.Now.AddYears(-2).Year</option>
                                        <option value="@DateTime.Now.AddYears(-3).Year">@DateTime.Now.AddYears(-3).Year</option>
                                        <option value="@DateTime.Now.AddYears(-4).Year">@DateTime.Now.AddYears(-4).Year</option>
                                        <option value="@DateTime.Now.AddYears(-5).Year">@DateTime.Now.AddYears(-5).Year</option>
                                        <option value="@DateTime.Now.AddYears(-6).Year">@DateTime.Now.AddYears(-6).Year</option>
                                        <option value="@DateTime.Now.AddYears(-7).Year">@DateTime.Now.AddYears(-7).Year</option>
                                        <option value="@DateTime.Now.AddYears(-8).Year">@DateTime.Now.AddYears(-8).Year</option>
                                        <option value="@DateTime.Now.AddYears(-9).Year">@DateTime.Now.AddYears(-9).Year</option>
                                    </select>
                                </div>
                                <div class="col-md-2 pull-right">
                                    <select asp-for="Period_1" class="form-control">
                                        <option value="1">January</option>
                                        <option value="2">Feburary</option>
                                        <option value="3">March</option>
                                        <option value="4">April</option>
                                        <option value="5">May</option>
                                        <option value="6">June</option>
                                        <option value="7">July</option>
                                        <option value="8">August</option>
                                        <option value="9">September</option>
                                        <option value="10">October</option>
                                        <option value="11">November</option>
                                        <option value="12">December</option>                                        
                                    </select>
                                </div>
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="submit" style="margin-right:50px"><span class="glyphicon glyphicon-search"></span></button>
                                </span>
                            </div>
                        </form>
                    </div>
                </div> 
                <div class="panel-body">
                    <div class="row">                        
                        <canvas id="myChart_1" width="1260" height="380"></canvas>                        
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row" style="padding-top:0px">
        <div class="col-lg-offset-4 col-lg-2">
            <div style="background-color:#b7bdff" title="Purchase"><p style="font-weight:bolder;text-align:center">Purchase</p></div>
        </div>
        <div class="col-lg-2">
            <div style="background-color:#f9cfe1" title="Sale"><p style="font-weight:bolder;text-align:center">Sale</p></div>
        </div>                
    </div>
</div>
 
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js"></script>
 
    <script> 
        $(document).ready(function () {            
              drawLineChart_1();
         });
 
        function drawLineChart_1() {
            var ctx = document.getElementById("myChart_1").getContext("2d");
            var myChart = new Chart(ctx).Line(data1_1);
        }

        var data1_1 = {
            labels: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31],
            datasets: [
               {
                   label: "Purchase View",
                   fillColor: "#b7bdff",
                   strokeColor: "darkblue",
                   pointColor: "darkblue",
                   pointStrokeColor: "#fff",
                   pointHighlightFill: "#fff",
                   pointHighlightStroke: "rgba(220,220,220,1)",
                   data:[@Model.Data]
               },
               {
                   label: "Sale View",
                   fillColor: "#f9cfe1",
                   strokeColor: "red",
                   pointColor: "red",
                   pointStrokeColor: "#e4cdf4",
                   pointHighlightFill: "#d8565d",                  
                   pointHighlightStroke: "rgba(220,220,220,1)",
                   data:[@Model.Data_1]
               }
            ]
        };
    </script>

src/Invento/Areas/Reports/Views/Analysis/PurchaseSaleViewYearly.cshtml
@model Invento.Areas.Reports.Models.AnalysisVM
@{
    ViewData["Title"] = "Analysis-Purchase Sale View Yearly";
    if (User.IsInRole("CompanyAdmin"))
    {
        Layout = "~/Views/Shared/_LayoutCompanyAdmin.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_LayoutCompanyUser.cshtml";
    }
}

<div>
    <div class="well" style="padding-bottom:5px">
        <div class="row">
            <span class="glyphicon glyphicon-stats glyphicon-bold " style="font-size: 1.5em; padding-left:10px;color:darkblue" aria-hidden="true"></span>
            <span style="font-family:'Times New Roman', Times, serif ; font-weight:bolder ; font-size:x-large ; margin-left:15px">Purchase Sale Analysis</span>
      </div>
    </div>
      
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                       <div > 
                            <form asp-action="PurchaseSaleViewYearly" asp-controller="Analysis" method="get" style="padding-top:0px">
                                <div class="input-group">
                                    <span class="panel-title">
                                        Purchase Sale Yearly Analysis
                                    </span>
                                    <input type="hidden" asp-for="LineChartType" value="0"/>
                                    <div class="col-md-2 pull-right">
                                        <select asp-for="Period" class="form-control">
                                            <option value="@DateTime.Now.Year">@DateTime.Now.Year</option>
                                            <option value="@DateTime.Now.AddYears(-1).Year">@DateTime.Now.AddYears(-1).Year</option>
                                            <option value="@DateTime.Now.AddYears(-2).Year">@DateTime.Now.AddYears(-2).Year</option>
                                            <option value="@DateTime.Now.AddYears(-3).Year">@DateTime.Now.AddYears(-3).Year</option>
                                            <option value="@DateTime.Now.AddYears(-4).Year">@DateTime.Now.AddYears(-4).Year</option>
                                            <option value="@DateTime.Now.AddYears(-5).Year">@DateTime.Now.AddYears(-5).Year</option>
                                            <option value="@DateTime.Now.AddYears(-6).Year">@DateTime.Now.AddYears(-6).Year</option>
                                            <option value="@DateTime.Now.AddYears(-7).Year">@DateTime.Now.AddYears(-7).Year</option>
                                            <option value="@DateTime.Now.AddYears(-8).Year">@DateTime.Now.AddYears(-8).Year</option>
                                            <option value="@DateTime.Now.AddYears(-9).Year">@DateTime.Now.AddYears(-9).Year</option>
                                        </select>
                                    </div>
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="submit" style="margin-right:50px"><span class="glyphicon glyphicon-search"></span></button>
                                    </span> 
                                </div>
                            </form>
                        </div>
                </div>
                <div class="panel-body">
                    <canvas id="myChart" width="1260" height="380"></canvas>
                </div>
            </div>
        </div>       
    </div>
    <div class="row" style="padding-top:0px">
        <div class="col-lg-offset-4 col-lg-2">
            <div style="background-color:#b7bdff" title="Purchase"><p style="font-weight:bolder;text-align:center">Purchase</p></div>
        </div>
        <div class="col-lg-2">
            <div style="background-color:#f9cfe1" title="Sale"><p style="font-weight:bolder;text-align:center">Sale</p></div>
        </div>
    </div>
     
</div>
 
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js"></script>
 
    <script> 
        $(document).ready(function () {            
            drawLineChart();
           
        });

        function drawLineChart() {
             var ctx = document.getElementById("myChart").getContext("2d");
             var myChart = new Chart(ctx).Line(data1);
        }

        var data1 = {
            labels: ["January", "February", "March", "April", "May", "June", "July","August","September","October","November","December"],
            datasets: [
              {
                  label: "Purchase View",
                  fillColor: "#b7bdff",
                  strokeColor: "darkblue",
                  pointColor: "darkblue",
                  pointStrokeColor: "#fff",
                  pointHighlightFill: "#fff",
                  pointHighlightStroke: "rgba(220,220,220,1)",
                  data:[@Model.Data]
              },
               {
                   label: "Sale View",
                   fillColor: "#f9cfe1",
                   strokeColor: "red",
                   pointColor: "red",
                   pointStrokeColor: "#e4cdf4",
                   pointHighlightFill: "#d8565d",
                   pointHighlightStroke: "rgba(220,220,220,1)",
                   data:[@Model.Data_1]
               }
            ]
        };
 
    </script>